name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.6.${{ github.run_number}}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and push OpenPassVault API
        uses: docker/build-push-action@v6
        with:
          file: Docker/api.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_DOCKER_IMAGE_NAME }}:${{ env.VERSION  }}

      - name: Build and push OpenPassVault Web
        uses: docker/build-push-action@v6
        with:
          file: Docker/web.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.WEB_DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.WEB_DOCKER_IMAGE_NAME }}:${{ env.VERSION  }}
